# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fee_termly_reg.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from models import session,fee_payed,Fees
import dialog
from PyQt5.QtWidgets import QApplication, QMainWindow
class Ui_MainWindow(QMainWindow,object):
    def submit_(self):
        if self.term_1.text() == '' or self.term_2.text()=='' or self.term_3.text()=='':
             Dialog = QtWidgets.QDialog()
             ui_dialog = dialog.Ui_Dialog()
             ui_dialog.win_title = 'Error'
             ui_dialog.title_="Null Error"
             ui_dialog.message_head=f"Value cannot be empty"
             ui_dialog.setupUi(Dialog)
        else:
                fees = Fees(total_term1=int(self.term_1.text()),total_term2=int(self.term_2.text()),total_term3=int(self.term_3.text()))
                #update current data
                old = session.query(Fees).filter_by(id=1).first()
                if old:
                     old.total_term1 = int(self.term_1.text())
                     old.total_term2 = int(self.term_2.text())
                     old.total_term3 = int(self.term_3.text())
                     session.commit()
                     
                elif not old:
                     session.add(fees)
                     session.commit()
                

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1021, 961))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/pexels-maxime-francis-2246476.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 40, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 87 22pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 191, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_3.setObjectName("label_3")
        self.term_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.term_1.setGeometry(QtCore.QRect(50, 190, 711, 71))
        self.term_1.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.term_1.setObjectName("term_1")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 511, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_4.setObjectName("label_4")
        self.term_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.term_2.setGeometry(QtCore.QRect(50, 350, 711, 71))
        self.term_2.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.term_2.setObjectName("term_2")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(50, 670, 271, 51))
        self.submit.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.submit.setObjectName("submit")
        self.submit.clicked.connect(self.submit_)
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(510, 670, 271, 51))
        self.cancel.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.cancel.setObjectName("cancel")
        self.cancel.clicked.connect(MainWindow.close)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 450, 511, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_5.setObjectName("label_5")
        self.term_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.term_3.setGeometry(QtCore.QRect(50, 520, 711, 71))
        self.term_3.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.term_3.setObjectName("term_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register Fees"))
        self.label_2.setText(_translate("MainWindow", "REGISTER FEES"))
        self.label_3.setText(_translate("MainWindow", "TERM ONE:"))
        self.label_4.setText(_translate("MainWindow", "TERM TWO:"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.label_5.setText(_translate("MainWindow", "TERM THREE:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
