# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from models import Classroom,session
import dialog
from PyQt5.QtWidgets import QApplication, QMainWindow
class Ui_Form(QMainWindow,object):
    def register(self):
        classrooms=session.query(Classroom).all()
        for clr in classrooms:
            if clr.form==self.form.currentText() and clr.stream==self.stream.text().upper():
                Dialog = QtWidgets.QDialog()
                ui_dialog = dialog.Ui_Dialog()
                ui_dialog.win_title = 'Error'
                ui_dialog.title_="Already Exists"
                ui_dialog.message_head=f"The class {clr.form} {clr.stream} already exists "
                ui_dialog.setupUi(Dialog)
                break
        else:
            new_classroom = Classroom(form=self.form.currentText(),stream=self.stream.text().upper())
            session.add(new_classroom)
            session.commit()
            self.stream.clear()
            Dialog = QtWidgets.QDialog()
            ui_dialog = dialog.Ui_Dialog()
            ui_dialog.win_title = 'Success'
            ui_dialog.title_="Success"
            ui_dialog.message_head=f"The information was delivered successfully."
            ui_dialog.setupUi(Dialog)

    def quit(self):
        import sys
        sys.exit(Ui_Form)
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(779, 759)
        Form.setMinimumSize(QtCore.QSize(779, 759))
        Form.setMaximumSize(QtCore.QSize(779, 759))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/660921-84.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(-10, 0, 791, 761))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/portfolio-8.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 20, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 75, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 320, 91, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.form = QtWidgets.QComboBox(Form)
        self.form.setGeometry(QtCore.QRect(20, 160, 571, 101))
        self.form.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.form.setObjectName("form")
        self.form.addItem("")
        self.form.addItem("")
        self.form.addItem("")
        self.form.addItem("")
        self.stream = QtWidgets.QLineEdit(Form)
        self.stream.setGeometry(QtCore.QRect(20, 370, 571, 71))
        self.stream.setStyleSheet("font: 87 10pt \"Segoe UI Black\";\n"
"")
        self.stream.setObjectName("stream")
        self.register_class = QtWidgets.QPushButton(Form)
        self.register_class.setGeometry(QtCore.QRect(20, 640, 191, 71))
        self.register_class.setStyleSheet("background-color: rgb(85, 255, 0);")
        self.register_class.setObjectName("register_class")
        self.register_class.clicked.connect(self.register)
        self.cancel = QtWidgets.QPushButton(Form)
        self.cancel.setGeometry(QtCore.QRect(550, 640, 191, 71))
        self.cancel.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.cancel.setObjectName("cancel")
        self.cancel.clicked.connect(Form.close)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
    
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Register Classroom"))
        self.label_2.setText(_translate("Form", "Register classroom"))
        self.label_3.setText(_translate("Form", "FORM:"))
        self.label_4.setText(_translate("Form", "STREAM:"))
        self.form.setItemText(0, _translate("Form", "Form 1"))
        self.form.setItemText(1, _translate("Form", "Form 2"))
        self.form.setItemText(2, _translate("Form", "Form 3"))
        self.form.setItemText(3, _translate("Form", "Form 4"))
        self.register_class.setText(_translate("Form", "Register"))
        self.cancel.setText(_translate("Form", "Cancel"))
        
        
        
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
