# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_teacher.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import dialog 
from models import Teachers,session
from datetime import datetime
from PyQt5.QtWidgets import QApplication, QMainWindow
class Ui_MainWindow(QMainWindow,object):
    def register(self):   
        if self.full_name.text()=='' or self.contacts.text()=='' or self.location.text()=='':
                Dialog = QtWidgets.QDialog()
                ui_dialog = dialog.Ui_Dialog()
                ui_dialog.win_title='Error'
                ui_dialog.title=f'The values cannot be null'
                ui_dialog.message_head='Please Enter values into the fields provided'
                ui_dialog.setupUi(Dialog)
                Dialog.show()
                Dialog.exec_()   
        else: 
                subjects = [
                self.maths,
                self.kiswahili,
                self.english,
                self.chemistry,
                self.biology,
                self.computer,
                self.music,
                self.business,
                self.physics,
                self.agriculture,
                self.geography,
                self.history,
                self.cre,
                self.other
                ]
                subjects_chosen = []
                for i in subjects:
                        if i.isChecked():
                                subjects_chosen.append(i.text())
                new_teacher = Teachers(full_name=self.full_name.text().upper(),contacts=self.contacts.text(),location=self.location.text().upper(),subjects=str(subjects_chosen),date_hired = datetime.now())
                session.add(new_teacher)
                session.commit()
                Dialog = QtWidgets.QDialog()
                ui_dialog = dialog.Ui_Dialog()
                ui_dialog.win_title='Success'
                ui_dialog.title=f'The data was entered successfully'
                ui_dialog.message_head='If you had any issues go to the help page or call the developer'
                ui_dialog.setupUi(Dialog)
                Dialog.show()
                Dialog.exec_()   
                
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/660921-84.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1021, 961))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/hero-bg.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 40, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 87 22pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 191, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_3.setObjectName("label_3")
        self.full_name = QtWidgets.QLineEdit(self.centralwidget)
        self.full_name.setGeometry(QtCore.QRect(50, 190, 711, 71))
        self.full_name.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.full_name.setObjectName("full_name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 511, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_4.setObjectName("label_4")
        self.contacts = QtWidgets.QLineEdit(self.centralwidget)
        self.contacts.setGeometry(QtCore.QRect(50, 350, 711, 71))
        self.contacts.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.contacts.setObjectName("contacts")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 450, 411, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 610, 191, 31))
        self.label_6.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_6.setObjectName("label_6")
        self.location = QtWidgets.QLineEdit(self.centralwidget)
        self.location.setGeometry(QtCore.QRect(50, 660, 711, 71))
        self.location.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.location.setObjectName("location")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(50, 820, 271, 51))
        self.submit.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.submit.setObjectName("submit")
        self.submit.clicked.connect(self.register)
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(510, 820, 271, 51))
        self.cancel.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.cancel.clicked.connect(MainWindow.close)
        self.cancel.setObjectName("cancel")
        self.maths = QtWidgets.QCheckBox(self.centralwidget)
        self.maths.setGeometry(QtCore.QRect(60, 490, 231, 41))
        self.maths.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.maths.setChecked(False)
        self.maths.setObjectName("maths")
        self.english = QtWidgets.QCheckBox(self.centralwidget)
        self.english.setGeometry(QtCore.QRect(60, 530, 231, 41))
        self.english.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.english.setChecked(False)
        self.english.setObjectName("english")
        self.kiswahili = QtWidgets.QCheckBox(self.centralwidget)
        self.kiswahili.setGeometry(QtCore.QRect(60, 570, 231, 41))
        self.kiswahili.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.kiswahili.setChecked(False)
        self.kiswahili.setObjectName("kiswahili")
        self.chemistry = QtWidgets.QCheckBox(self.centralwidget)
        self.chemistry.setGeometry(QtCore.QRect(260, 490, 231, 41))
        self.chemistry.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.chemistry.setChecked(False)
        self.chemistry.setObjectName("chemistry")
        self.biology = QtWidgets.QCheckBox(self.centralwidget)
        self.biology.setGeometry(QtCore.QRect(260, 530, 231, 41))
        self.biology.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.biology.setChecked(False)
        self.biology.setObjectName("biology")
        self.physics = QtWidgets.QCheckBox(self.centralwidget)
        self.physics.setGeometry(QtCore.QRect(260, 570, 231, 41))
        self.physics.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.physics.setChecked(False)
        self.physics.setObjectName("physics")
        self.history = QtWidgets.QCheckBox(self.centralwidget)
        self.history.setGeometry(QtCore.QRect(450, 490, 231, 41))
        self.history.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.history.setChecked(False)
        self.history.setObjectName("history")
        self.geography = QtWidgets.QCheckBox(self.centralwidget)
        self.geography.setGeometry(QtCore.QRect(450, 530, 231, 41))
        self.geography.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.geography.setChecked(False)
        self.geography.setObjectName("geography")
        self.cre = QtWidgets.QCheckBox(self.centralwidget)
        self.cre.setGeometry(QtCore.QRect(450, 570, 161, 41))
        self.cre.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.cre.setChecked(False)
        self.cre.setObjectName("cre")
        self.business = QtWidgets.QCheckBox(self.centralwidget)
        self.business.setGeometry(QtCore.QRect(620, 490, 231, 41))
        self.business.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.business.setChecked(False)
        self.business.setObjectName("business")
        self.agriculture = QtWidgets.QCheckBox(self.centralwidget)
        self.agriculture.setGeometry(QtCore.QRect(620, 530, 231, 41))
        self.agriculture.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.agriculture.setChecked(False)
        self.agriculture.setObjectName("agriculture")
        self.home_science = QtWidgets.QCheckBox(self.centralwidget)
        self.home_science.setGeometry(QtCore.QRect(620, 570, 231, 41))
        self.home_science.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.home_science.setChecked(False)
        self.home_science.setObjectName("home_science")
        self.computer = QtWidgets.QCheckBox(self.centralwidget)
        self.computer.setGeometry(QtCore.QRect(820, 490, 231, 41))
        self.computer.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.computer.setChecked(False)
        self.computer.setObjectName("computer")
        self.music = QtWidgets.QCheckBox(self.centralwidget)
        self.music.setGeometry(QtCore.QRect(820, 530, 231, 41))
        self.music.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.music.setChecked(False)
        self.music.setObjectName("music")
        self.other = QtWidgets.QCheckBox(self.centralwidget)
        self.other.setGeometry(QtCore.QRect(820, 570, 231, 41))
        self.other.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 255, 0);")
        self.other.setChecked(False)
        self.other.setObjectName("other")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register Teacher"))
        self.label_2.setText(_translate("MainWindow", "REGISTER TEACHER"))
        self.label_3.setText(_translate("MainWindow", "Full Name:"))
        self.label_4.setText(_translate("MainWindow", "Contacts:"))
        self.label_5.setText(_translate("MainWindow", "Subjects Taught:"))
        self.label_6.setText(_translate("MainWindow", "Location:"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.maths.setText(_translate("MainWindow", "Mathematics"))
        self.english.setText(_translate("MainWindow", "English"))
        self.kiswahili.setText(_translate("MainWindow", "Kiswahili"))
        self.chemistry.setText(_translate("MainWindow", "Chemistry"))
        self.biology.setText(_translate("MainWindow", "Biology"))
        self.physics.setText(_translate("MainWindow", "Physics"))
        self.history.setText(_translate("MainWindow", "History"))
        self.geography.setText(_translate("MainWindow", "Geography"))
        self.cre.setText(_translate("MainWindow", "CRE"))
        self.business.setText(_translate("MainWindow", "Business"))
        self.agriculture.setText(_translate("MainWindow", "Agriculture"))
        self.home_science.setText(_translate("MainWindow", "HomeScience"))
        self.computer.setText(_translate("MainWindow", "Computer"))
        self.music.setText(_translate("MainWindow", "Music"))
        self.other.setText(_translate("MainWindow", "other"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
