# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student_library.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from models import session,Library,bookTaken,Students
import dialog
from PyQt5.QtWidgets import QApplication, QMainWindow
class Ui_MainWindow(QMainWindow,object):
    def book_taken(self):
        student =  session.query(Students).filter_by(index_no = int(self.adm_no.text())).first()
        if student:
            # Register the book
            books = bookTaken(title=self.book_title.text().upper(),adm=int(self.adm_no.text()),name=self.full_name.text().upper(),status=self.status.currentText())
            session.add(books)
            session.commit()
            Dialog = QtWidgets.QDialog()
            ui_dialog = dialog.Ui_Dialog()
            ui_dialog.win_title = 'Success'
            ui_dialog.title_="ACTION SUCCESSFULL"
            ui_dialog.message_head="Student who took the book was successfully added to database"
            ui_dialog.setupUi(Dialog)
            Dialog.show() 
            Dialog.exec_()
        else:
            Dialog = QtWidgets.QDialog()
            ui_dialog = dialog.Ui_Dialog()
            ui_dialog.win_title = 'Error'
            ui_dialog.title_="404 NOT FOUND"
            ui_dialog.message_head="The students admission number does not exist"
            ui_dialog.setupUi(Dialog)
            Dialog.show() 
            Dialog.exec_()
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 1000))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 1000))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("imgs/660921-84.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1021, 961))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imgs/pexels-maxime-francis-2246476.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 40, 481, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font: 87 22pt \"Segoe UI Black\";\n"
"color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 191, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_3.setObjectName("label_3")
        self.full_name = QtWidgets.QLineEdit(self.centralwidget)
        self.full_name.setGeometry(QtCore.QRect(50, 190, 711, 71))
        self.full_name.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.full_name.setObjectName("full_name")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 280, 511, 31))
        self.label_4.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_4.setObjectName("label_4")
        self.adm_no = QtWidgets.QLineEdit(self.centralwidget)
        self.adm_no.setGeometry(QtCore.QRect(50, 350, 711, 71))
        self.adm_no.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.adm_no.setObjectName("adm_no")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 450, 411, 31))
        self.label_5.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_5.setObjectName("label_5")
        self.book_title = QtWidgets.QLineEdit(self.centralwidget)
        self.book_title.setGeometry(QtCore.QRect(50, 500, 711, 71))
        self.book_title.setStyleSheet("font: 20pt \"Segoe MDL2 Assets\";")
        self.book_title.setText("")
        self.book_title.setObjectName("book_title")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(50, 620, 191, 31))
        self.label_7.setStyleSheet("color: rgb(255, 255, 0);\n"
"font: 87 12pt \"Segoe UI Black\";")
        self.label_7.setObjectName("label_7")
        self.status = QtWidgets.QComboBox(self.centralwidget)
        self.status.setGeometry(QtCore.QRect(50, 670, 691, 51))
        self.status.setObjectName("status")
        self.status.addItem("")
        self.status.addItem("")
        self.submit = QtWidgets.QPushButton(self.centralwidget)
        self.submit.setGeometry(QtCore.QRect(50, 790, 271, 51))
        self.submit.setStyleSheet("background-color: rgb(255, 85, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.submit.setObjectName("submit")
        self.submit.clicked.connect(self.book_taken)
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(510, 790, 271, 51))
        self.cancel.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 11pt \"MS Shell Dlg 2\";")
        self.cancel.clicked.connect(MainWindow.close)
        self.cancel.setObjectName("cancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Students Status in Library"))
        self.label_2.setText(_translate("MainWindow", "LIBRARY"))
        self.label_3.setText(_translate("MainWindow", "Full Name:"))
        self.label_4.setText(_translate("MainWindow", "Admission number:"))
        self.label_5.setText(_translate("MainWindow", "Book Title:"))
        self.label_7.setText(_translate("MainWindow", "Status:"))
        self.status.setItemText(0, _translate("MainWindow", "Took a book"))
        self.status.setItemText(1, _translate("MainWindow", "Returned a book"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
